name: Root Monitor

# Execute this as a daily cron job.
on:
  # Enable cron for checking metadata is not due to expire soon
  schedule:
    - cron: '0 0 */1 * *' # every day
  workflow_dispatch:

jobs:
  root-probe:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: 1.17.7
      - name: Install verify
        run: go install github.com/sigstore/root-signing/...@latest

      # Check expiration in less than 3 days
      - name: Check expiration
        run: |
          export EXPIRY=$(date -d '+3 days' '+%Y/%m/%d')
          verify repository --gcs --repository sigstore-tuf-root --root ceremony/2021-06-18/repository/root.json --valid-until ${EXPIRY}

  slack-notification:
    name: Slack Notification On Failure
    runs-on: ubuntu-latest

    needs: [root-probe]
    if: failure()

    steps:
    - name: Set message
      id: message
      run: |
        echo "::set-output name=root_state::failure"

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # v2.2.0
      env:
        SLACK_USERNAME: Sigstore probe
        SLACK_ICON: https://next.redhat.com/wp-content/uploads/2021/10/Symbol_200x200.png
        SLACK_COLOR: '#d40404' # red
        SLACK_MESSAGE: "GCS Root: ${{ steps.message.outputs.root_state }}. See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}